import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Archivo_Black, JetBrains_Mono } from "next/font/google";
import { cn } from "@/lib/utils";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "next-themes";

const archivoBlack = Archivo_Black({
  subsets: ["latin"],
  variable: "--font-archivo-black",
  weight: "400",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ResumeIQ — Resume Intelligence Platform",
  description:
    "Upload your resume, get AI-powered feedback with ATS score, section analysis, and download an improved resume generated by Gemini.",
  openGraph: {
    title: "ResumeIQ",
    description: "Resume Intelligence Platform — Score, Analyze, Rebuild.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "scroll-smooth",
        archivoBlack.variable,
        jetbrainsMono.variable,
        geistSans.variable,
        geistMono.variable
      )}
      suppressHydrationWarning
    >
      <head />
      <body className="bg-[var(--background)] text-[var(--foreground)] antialiased font-[var(--font-archivo-black)] font-medium">
        {/* ThemeProvider applies .dark or .light class to <html> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          themes={["light", "dark"]}
        >
          <AuthProvider>{children}</AuthProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
